// Minimal sdkconfig.h for ESP32 project
#pragma once

// Basic ESP32 configuration
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_ESPTOOLPY_FLASHSIZE "4MB"

// BLE related configs
#define CONFIG_BT_ENABLED 1
#define CONFIG_BTDM_CTRL_MODE_BLE_ONLY 1
#define CONFIG_BT_BLUEDROID_ENABLED 1

// Allow for larger application size
#define CONFIG_PARTITION_TABLE_CUSTOM 1
#define CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions.csv"

// TFT related configs
#define CONFIG_SPI_MASTER_ISR_IN_IRAM 1

// Arduino specific configs
#define CONFIG_ARDUINO_SELECTIVE_COMPILATION 1
#define CONFIG_ARDUINO_SELECTIVE_ArduinoOTA 1
#define CONFIG_ARDUINO_SELECTIVE_BLE 1
#define CONFIG_ARDUINO_SELECTIVE_BluetoothSerial 1
#define CONFIG_ARDUINO_SELECTIVE_DNSServer 1
#define CONFIG_ARDUINO_SELECTIVE_EEPROM 1
#define CONFIG_ARDUINO_SELECTIVE_ESP32 1
#define CONFIG_ARDUINO_SELECTIVE_ESPmDNS 1
#define CONFIG_ARDUINO_SELECTIVE_FFat 1
#define CONFIG_ARDUINO_SELECTIVE_FS 1
#define CONFIG_ARDUINO_SELECTIVE_HTTPClient 1
#define CONFIG_ARDUINO_SELECTIVE_LITTLEFS 1
#define CONFIG_ARDUINO_SELECTIVE_NetBIOS 1
#define CONFIG_ARDUINO_SELECTIVE_Preferences 1
#define CONFIG_ARDUINO_SELECTIVE_SD 1
#define CONFIG_ARDUINO_SELECTIVE_SD_MMC 1
#define CONFIG_ARDUINO_SELECTIVE_SimpleBLE 1
#define CONFIG_ARDUINO_SELECTIVE_SPI 1
#define CONFIG_ARDUINO_SELECTIVE_SPIFFS 1
#define CONFIG_ARDUINO_SELECTIVE_Update 1
#define CONFIG_ARDUINO_SELECTIVE_WebServer 1
#define CONFIG_ARDUINO_SELECTIVE_WiFi 1
#define CONFIG_ARDUINO_SELECTIVE_WiFiClientSecure 1
#define CONFIG_ARDUINO_SELECTIVE_WiFiProv 1
#define CONFIG_ARDUINO_SELECTIVE_Wire 1
